MovieShop.MVC/Models/ErrorViewModel.cs
using System;

namespace MovieShop.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShop.MVC/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MovieShop.Core.Models.Request;
using MovieShop.Core.ServiceInterface;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace MovieShop.MVC.Controllers
{
	public class AccountController : Controller
	{
		private readonly IUserService _userService;
        public AccountController(IUserService userService)
        {
			_userService = userService;
        }

		[HttpGet]
		public async Task<IActionResult> Login()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Login(LoginRequestModel loginRequest, string returnUrl = null)
        {
			// 1. id rreturnUrl === null then we go to home page
			//    otherwise go the retuenUrl
			returnUrl ??= Url.Content("~/");

			if (!ModelState.IsValid)
			{
				return View();
			}
			var user = await _userService.ValidateUser(loginRequest);
			if (user == null)
			{
				ModelState.AddModelError(string.Empty, "Please check username and password");
				return View();
			}


			// if un/pw is success

			// Cookie based Authentication
			// Create a cookie with some information such that id, firstname, lastname, roles etc. CLAIMS
			// that information should not be in plain text, it should be encrypted

			// send this loginRequest to the UserService that will validate the un/pw

			var claims = new List<Claim>
			{
				new Claim(ClaimTypes.Name, user.Email),
				new Claim(ClaimTypes.GivenName, user.FirstName),
				new Claim(ClaimTypes.Surname, user.LastName),
				new Claim(ClaimTypes.DateOfBirth, user.DateOfBirth.Value.ToShortDateString()),
				new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
			};

			var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
				new ClaimsPrincipal(claimsIdentity));

			return LocalRedirect(returnUrl);
		}
		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();
			return RedirectToAction("Login");
		}

		[HttpGet]
		public async Task<IActionResult> Register()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Register(UserRegisterRequestModel requestModel)
		{
			// Model Binding
			// Form, it will look for input elements names and if those names match with our Action menthod model
			// properties
			// then it will automatically map that data

			// a control with name=EMAIL "abc@abc.com"
			// UserRegisterRequestModel => Email

			if (!ModelState.IsValid)
			{
				return View();
			}
			// only when every validaiton passes make sure you save to database
			// call our User Service to save to Db
			var createdUser = await _userService.RegisterUser(requestModel);
			if (createdUser)
			{
				return RedirectToAction("Login");
			}
			return View();
		}


	}
}

MovieShop.MVC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShop.MVC.Controllers
{
    public class AdminController : Controller
    {
        //[Authorize(Roles = "Admin"]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MovieShop.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieShop.Core.ServiceInterface;
using MovieShop.MVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShop.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMovieService _movieService;

        public HomeController(ILogger<HomeController> logger, IMovieService movieService)
        {
            _logger = logger;
            _movieService = movieService;
        }

        public async Task<IActionResult> Index()
        {
            // get the movies from movie service and send those list of movies to the View
            var topMovies = await _movieService.GetTop25GrossingMovies();
            // ViewBag, ViewData and Models
            return View(topMovies);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShop.MVC/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MovieShop.Core.ServiceInterface;

namespace MovieShop.MVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            // call the Movie service that will call Movie Repository
            var movieDetails = await _movieService.GetMovieById(id);
            return View(movieDetails);
        }
    }
}

MovieShop.MVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using MovieShop.Core.Models.Request;
using MovieShop.Core.ServiceInterface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShop.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;

        public UserController(IMovieService movieService, IUserService userService)
        {
            _movieService = movieService;
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> BuyMovie(int id)
        {
            var movie = await _movieService.GetMovieById(id);
            return View(movie);
        }

        [HttpPost]
        public async Task<IActionResult> BuyMovie(PurchaseRequestModel purchase)
        {
            await _userService.PurchaseMovie(purchase);
            return Ok();
        }

        // call this method when user clicks on Buy Movie in Movie details page
        // Filters,

        //[HttpGet]
        //[Authorize]
        // public async Task<IActionResult> BuyMovie(int id)
        // {
        //     var movie = await _movieService.GetMovieById(id);
        //     // call uerService to save the movie that will call repository, that will save in Purchase Table
        //     return View();
        // }
    }
}

MovieShop.MVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieShop.Core.ServiceInterface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShop.MVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent: ViewComponent
    {
        private readonly IGenreService _genreService;
        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            // by conention it will look for a view name Default.cshtml
            return View(genres);
        }
    }
}

MovieShop.MVC/Views/Home/Index.cshtml
@model IEnumerable<MovieShop.Core.Models.Response.MovieCardResponseModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    <partial name="_MovieCard" model="movie" />
                </div>
             }              

        </div>
    </div>
</div>

MovieShop.MVC/Views/Movies/Details.cshtml
@model MovieShop.Core.Models.Response.MovieDetailsResponseModel

@{ 
    ViewData["Title"] = "Details";
}

<div class="bg-dark w-100">
    <div class="row">
        <div class="col">
            <div>
                <img src="@Model.PosterUrl" alt=@Model.Title" />
            </div>
        </div>      
        <div class="col-md-6">
            <div class="row mt-2">
                <div class="col-12">
                    <h1 class="text-white text-center">
                        @Model.Title
                    </h1>
                    <small class="text-muted">
                        @Model.Tagline
                    </small>
                </div>
            </div>
            <div class="row">
                <div class="col-4 text-secondary font-weight-bold mt-2">
                    @Model.RunTime m| @Model.ReleaseDate.Value.Date.Year
                </div>
                <div class="col-8 bg-dark text-white">
                    @foreach (var genre in Model.Genres)
                    {
                        <a class="badge badge-pill badge-dark ml-1" asp-action="Genre" asp-route-id="@genre.Id">
                            @genre.Name
                        </a>
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-light mt-2">
                    @Model.Overview
                </div>
            </div>
        </div>

        <div class="col">
            <ul class="list-group">
                <li class="list-group-item">
                    <button type="button" class="btn btn-outline-dark bg-dark text-white btn-block" btn-sm>
                        <i class="far fa-edit mr-1"></i>
                        REVIEW
                    </button>
                </li>
                <li class="list-group-item">
                    <button type="button" class="btn btn-outline-dark bg-dark text-white btn-block" btn-sm>
                        <i class="far fa-edit mr-1"></i>
                        TRAILER
                    </button>
                </li>
                <li class="list-group-item">
                    <button type="button" class="btn btn-outline-dark btn-light btn-lg btn-block btn-sm" asp-route-id="@Model.Id" asp-controller="User" asp-action="BuyMovie">
                        BUY @Model.Price
                    </button>
                    <button type="button" class="btn btn-outline-dark btn-light btn-lg btn-block btn-sm">
                        WATCH MOVIE
                    </button>
                </li>
            </ul>
        </div>
    </div>

</div>

MovieShop.MVC/Views/Movies/Index.cshtml
<h1>
    Movie Index Page
</h1>

MovieShop.MVC/Views/Movies/TopRevenueMovies.cshtml
<h2>
    Top Revenue Movies
</h2>

MovieShop.MVC/Views/Shared/Components/Genres/Default.cshtml
@model IEnumerable<MovieShop.Core.Entities.Genre>

@foreach(var genre in Model){
    <a class="dropdown-item" asp-controller="Movies" asp-action="genre" asp-route-id="@genre.Id">
    @genre.Name
    </a>
}

MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShop.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShop.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Genres
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                @await Component.InvokeAsync("Genres") 
                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShop.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShop.MVC/Views/Shared/_MovieCard.cshtml
@model MovieShop.Core.Models.Response.MovieCardResponseModel

@*when u click on the poster go to MovieController, Details action method and send movie id*@

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" alt="@Model.Title" class="img-fluid" />
    </a>
</div>